name = "IrregularDelimitedFiles"
uuid = "49c2a1e4-4248-42d5-ba11-d61d1cad7a0c"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"

[compat]
julia = "1.6"